# Generated by Django 4.0.1 on 2023-08-14 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import server.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=50)),
                ('nickName', models.CharField(blank=True, max_length=15)),
                ('rollNumber', models.CharField(max_length=50, unique=True)),
                ('mobileNumber', models.CharField(max_length=20)),
                ('roomNumber', models.CharField(blank=True, max_length=3)),
                ('RFID', models.CharField(blank=True, max_length=10)),
                ('photo', models.ImageField(blank=True, upload_to=server.models.image_handler)),
                ('isCompleted', models.BooleanField(default=False)),
                ('isVerified', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['roomNumber'],
            },
        ),
        migrations.CreateModel(
            name='Council',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('por', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=15)),
                ('image', models.ImageField(default='default.jpg', upload_to=server.models.council_handler)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('post', models.ImageField(upload_to=server.models.post_handler)),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.TextField(max_length=500)),
                ('likes', models.IntegerField()),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='HostelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=server.models.hostelfile_handler)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('Cult', 'Cult'), ('Sports', 'Sports'), ('Tech', 'Tech')], max_length=10)),
                ('heading', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['domain'],
            },
        ),
        migrations.CreateModel(
            name='MessMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=server.models.menu_handler)),
                ('start', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['start'],
            },
        ),
        migrations.CreateModel(
            name='OtherImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, validators=[server.models.image_name_validation])),
                ('image', models.ImageField(upload_to=server.models.otherimages)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast', models.CharField(blank=True, max_length=6, null=True)),
                ('lunch', models.CharField(blank=True, max_length=6, null=True)),
                ('snacks', models.CharField(blank=True, max_length=6, null=True)),
                ('dinner', models.CharField(blank=True, max_length=6, null=True)),
                ('date', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'student__rollNumber'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('photo', models.ImageField(default='static/none.jpg', upload_to=server.models.inventory_handler)),
                ('damage_reports', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.inventorycategory')),
            ],
            options={
                'ordering': ['item__domain'],
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('Mess', 'Mess'), ('Maint', 'Maintanence'), ('Sports', 'Sports'), ('Tech', 'Tech'), ('Network', 'Network')], max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, upload_to=server.models.complaint_handler)),
                ('details', models.TextField(max_length=200)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
