# Generated by Django 4.0.1 on 2023-08-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelfile',
            name='name',
            field=models.CharField(default='File', max_length=15),
            preserve_default=False,
        ),
    ]
